name: Update Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check for PAT token
        id: check-token
        run: |
          if [ -n "${{ secrets.PAT_TOKEN }}" ]; then
            echo "has_pat=true" >> $GITHUB_OUTPUT
          else
            echo "has_pat=false" >> $GITHUB_OUTPUT
          fi
            
      - name: Checkout with PAT
        if: steps.check-token.outputs.has_pat == 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Checkout with GITHUB_TOKEN
        if: steps.check-token.outputs.has_pat != 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and Push (with PAT)
        if: steps.check-token.outputs.has_pat == 'true'
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Set the remote URL with the PAT token
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/beshkenadze/eyecite-js.git
          
          # Check if CHANGELOG.md exists and has changes
          if [ -f CHANGELOG.md ]; then
            git add CHANGELOG.md
            if git diff --cached --quiet; then
              echo "No changes to CHANGELOG.md"
            else
              git commit -m "docs: update CHANGELOG.md [skip ci]"
              git push origin main
            fi
          else
            echo "CHANGELOG.md was not generated"
            exit 1
          fi
          
      - name: Create Pull Request (without PAT)
        if: steps.check-token.outputs.has_pat != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update CHANGELOG.md [skip ci]"
          title: "docs: update CHANGELOG.md"
          body: |
            ## 📝 Automated Changelog Update
            
            This PR updates the CHANGELOG.md file with the latest changes.
            
            Generated by [git-cliff](https://github.com/orhun/git-cliff).
          branch: changelog-update
          delete-branch: true