name: Update Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and Push
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Check if CHANGELOG.md exists and has changes
          if [ -f CHANGELOG.md ]; then
            git add CHANGELOG.md
            if git diff --cached --quiet; then
              echo "No changes to CHANGELOG.md"
            else
              git commit -m "docs: update CHANGELOG.md [skip ci]"
              git push origin main
            fi
          else
            echo "CHANGELOG.md was not generated"
            exit 1
          fi