name: Update Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use PAT if available for protected branch, otherwise GITHUB_TOKEN
          token: ${{ secrets.PAT_TOKEN || github.token }}
          
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update CHANGELOG.md"
          file_pattern: CHANGELOG.md
          # Use human-readable bot name
          commit_user_name: Eyecite Bot
          commit_user_email: eyecite-bot@users.noreply.github.com
          commit_author: Eyecite Bot <eyecite-bot@users.noreply.github.com>
          # Skip CI to prevent recursive runs
          commit_options: '--no-verify --signoff'
          add_options: '-u'
          push_options: '--force-with-lease'
          skip_dirty_check: false
          skip_fetch: false
          skip_checkout: false
          disable_globbing: false
          create_branch: false