name: Update Changelog

on:
  # Only run on version tags and releases, NOT on every push!
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use PAT if available for protected branch, otherwise GITHUB_TOKEN
          token: ${{ secrets.PAT_TOKEN || github.token }}
          
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Option 1: Use web-flow signed commits (Recommended)
      - name: Commit and Push Changes (Verified)
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          files: |
            CHANGELOG.md
          commit-message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          ref: refs/heads/main
          
      # Option 2: Alternative using EndBug action (fallback)
      # - name: Commit and Push Changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
      #     add: 'CHANGELOG.md'
      #     default_author: github_actions
      #     push: true
      #     github_token: ${{ secrets.PAT_TOKEN }}