name: Update Changelog via PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update CHANGELOG.md"
          title: "docs: update CHANGELOG.md"
          body: |
            ## 📝 Automated Changelog Update
            
            This PR updates the CHANGELOG.md file with the latest changes from git history.
            
            Generated by [git-cliff](https://github.com/orhun/git-cliff).
          branch: changelog-update
          delete-branch: true
          labels: |
            documentation
            automated