name: Example Signed Commit

on:
  workflow_dispatch:

jobs:
  # Method 1: Using GitHub's web-flow GPG key (automatic signing)
  signed-commit-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Make changes
        run: echo "test" > test.txt
        
      # This action creates verified commits using GitHub's API
      - name: Create Verified Commit
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            test.txt
          commit-message: "chore: test signed commit"
          ref: ${{ github.ref }}

  # Method 2: Import GPG key for signing
  signed-commit-gpg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          
      - name: Make changes
        run: echo "test" > test.txt
        
      - name: Commit with GPG signature
        run: |
          git add test.txt
          git commit -S -m "chore: test GPG signed commit"
          git push

  # Method 3: Using verified-bot-commit action
  signed-commit-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Make changes
        run: echo "test" > test.txt
        
      - name: Create Verified Bot Commit
        uses: IAreKyleW00t/verified-bot-commit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: test.txt
          commit-message: "chore: test verified bot commit"